name: 'Fedora install'
description: 'Install packages using dnf. Assumes that it is running on a Fedora image'
inputs:
  builddep:
    description: 'Install builddep for the given package'
    required: false
    default: ''
  packages:
    description: 'Packages to install'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install.sh ${{ inputs.packages }} ${{ inputs.builddep }}
      shell: bash
