name: 'Fedora install'
description: 'Install packages using dnf. Assumes that it is running on a Fedora image'
inputs:
  builddep:
    description: 'Install builddep for the given package'
    required: false
    default: ''
  packages:
    description: 'Packages to install'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
           dnf -y update
      shell: bash
    - if: ${{ inputs.builddep != '' }}
      run: |
           dnf -y install 'dnf-command(builddep)'
           dnf -y builddep ${{ inputs.builddep }}
      shell: bash
    - if: ${{ inputs.packages != '' }}
      run: |
           dnf -y install ${{ inputs.packages }}
      shell: bash
